[PATH]
#/path/to/images-for-training
IMAGE_PATH = training_data/image
#/path/to/labels-for-training
#LABEL_PATH = training_data/grae_nuevo_labels/ 
LABEL_PATH = training_data/nouveaux_labels/
#Beware, this parameter is for both training and for inference...

#path/to/weights.pth
#MODEL_PARAMS = training_data/model_weights/2025-10-10_14:43:51.pth
#MODEL_PARAMS = training_data/model_weights/unet_grain_grae_nuevo_test.pth
MODEL_PARAMS = training_data/model_weights/unet_grain_nouveaux_test_95.pth

#These parameters are ~1:1 from the original paper
[TRAINING_PARAMS]
BATCH_SIZE = 5 
EPOCHS = 100
#determines the amount of cores assigned to training
NUM_WORKERS = 0 
LEARNING_RATE = 0.0001
#stores checkpoints of your model 
SAVING_RATE = 5

#for advanced use only:
PRETRAINED_WEIGHTS = 
CUSTOM_LOSS_FUNCTION = 

#These are recommended parameters
[DATA_PARAMS]
AUGMENT_ACTIVE = 0
TRAINING_SPLIT = 0.9

[INFERENCE_PARAMS]
INFERENCE = 1
#N_TEST_DATA_DIR = training_data/
#N_TEST_PATTERN = image/*.png
N_TEST_DATA_DIR = Wayne_validation_data/
N_TEST_PATTERN = validation/*/aligned/*.png
#images should be square 
OUTPUT_RESOLUTION = 256 
#OVERLAY_DATA_DIR = /where/to/put
#OVERLAY_DATA_DIR =  training_data/predict_unet_grain_grae_nuevo_test_resolution_256/
#FINAL_OUTPUT_DIR =  training_data/predict_unet_grain_grae_nuevo_test_resolution_256/output/

OVERLAY_DATA_DIR =  Wayne_validation_data/
FINAL_OUTPUT_DIR =  training_data/predict_unet_grain_nouveaux_test_on_Wayne_validation_data_95_256/output/



#These are parameters for adjusting the output segmentation post-processing
#Use 1 for true and 0 or blank for false. Tune using your judgement, or optimize in an intelligent way... Up to you.
[POST_PROCESS]
POST_PROCESS = 1
COMPILATION = min
N_DILATIONS = 3
LIBERAL_THRESHOLD = 161
CONSERVATIVE_THRESHOLD = 212 
INVERT_DOUBLE_THRESHOLD = True
MIN_GRAIN_AREA = 100
PRUNE_SIZE = 30